- name: 强制覆盖内核版本号（修复显示不全）
  run: |
    cd kernel_workspace/common
    echo "EXTRAVERSION = -android15-8-gf4dc45704e54-abogki446052083-4k" >> Makefile
    sed -i 's/^CONFIG_LOCALVERSION.*/CONFIG_LOCALVERSION=""/' arch/arm64/configs/gki_defconfig
    echo "CONFIG_LOCALVERSION_AUTO=n" >> arch/arm64/configs/gki_defconfig
